### ISSUE TITLE
Does not work correctly with the new version of Sodium

### ISSUE THREAD

**Issue by forditt** [tyrannus00/CleanF3#12]
Does not hide information mod sodium, version - [Sodium 0.5.1](https://modrinth.com/mod/sodium/version/mc1.20.1-0.5.1)
![image](https://github.com/tyrannus00/CleanF3/assets/105544922/042f2d38-f2f8-41d7-9d7b-5e895cb54d7a)

**Comment by tyrannus00** [comment]
A version with the fix has been uploaded :)
