### ISSUE TITLE
"Too Many Separators" Between Lines

### ISSUE THREAD

**Issue by LobbyLC** [tyrannus00/CleanF3#13]
Due to the method Clean F3 uses to hide unwanted lines, the debug menu ends up with more separators than intended. The ability to prevent multiple consecutive separators would be awesome to have!

- I made the "Correct" image in Paint so it's not perfect, but you should get the idea
- Additionally, if you're looking to add more mod compatibility, being able to hide ModernFix and ImmediatelyFast's lines entirely would also be pretty neat!

| Current             | Correct               |
|:---------------------:|:---------------------:|
| ![Clean F3 Current](https://github.com/tyrannus00/CleanF3/assets/116382138/60e0d0f7-6d44-4599-944c-20ed6f6e37ec)            | ![Clean F3 Correct](https://github.com/tyrannus00/CleanF3/assets/116382138/4a74c38e-207c-4765-8f86-c06703d637f5)              |

**Comment by forditt** [comment]
You can exclude the display of `ImmediatelyFast` information in its config -  `"dont_add_info_into_debug_hud": true,`

**Comment by LobbyLC** [comment]
Oh, handy! I must've missed that, though the main point of this post still stands. The "extra separators" are something I can't help but notice whenever I open my debug menu with the mod enabled so I thought I'd report it as an issue haha.

**Comment by tyrannus00** [comment]
I released a version where this is fixed, and I also added an option to hide the ModernFix watermark :)
