### ISSUE TITLE
Config request - option to remove more vanilla debug info

### ISSUE THREAD

**Issue by anoomolu** [tyrannus00/CleanF3#16]
Hiya, first off thank you for making such a useful mod!

I was wondering if you'd be willing to add a couple more options for removing F3 info, some of them in line with the vanilla reduced debug info gamerule:
- CH, SH and Biome Builder. I think most players don't need/use this info at all.
- Block/Chunk coords (the ones below XYZ). F3+G is usually more useful/relevant for players
- Chunks[C] and Chunks[V]. Maybe leave this off by default since some might find it useful?
- Hunger - a lot of modded players use Appleskin to see hunger, saturation and exhaustion anyways
- Sounds and local difficulty
- Dimension/FC - biome already tells you this info

Also, [Dynamic FPS](https://modrinth.com/mod/dynamic-fps) adds a line when the Minecraft window is unfocused, which is hidden when returning to game and shifts every F3 line up a bit - would it be possible to add a config to hide this? If you disagree with any of the suggestions then no worries, thanks for taking the time to read this <3

![image](https://github.com/tyrannus00/CleanF3/assets/77850233/06789ecc-2811-4dc0-8826-8fa1c9109360)

**Comment by tyrannus00** [comment]
Thank you for your suggestion, I added a toggle for dynamic fps.
About the other things, I didn't split them up into seperate options each, as I feel like that would be unnecessary bloat, instead I made one setting to "only show the necessary". I made it not hide the Local Difficulty line though, as I feel like that is still useful to a lot of people.
