### ISSUE TITLE
Appleskin support

### ISSUE THREAD

**Issue by BluebirdYT** [tyrannus00/CleanF3#20]
[Appleskin](https://modrinth.com/mod/appleskin) adds pretty useless information about hunger bar in the f3 screen. I was wondering if you could add support to remove it with this mod?

![image](https://github.com/tyrannus00/CleanF3/assets/76973207/48b0b148-4508-4d96-a669-d38cedfc5f3d)

**Comment by tyrannus00** [comment]
Appleskin already has a config option called "Show food values in debug screen" to disable this, so it isn't needed for CleanF3
