### ISSUE TITLE
Hiding Distant Horizons info doesn't seem to be working anymore

### ISSUE THREAD

**Issue by pajicadvance** [tyrannus00/CleanF3#27]
Not sure when this changed, but with the latest version of Distant Horizons, the debug info for the mod is still displayed, even with the option enabled in CleanF3.
![2024-10-11_21 47 21](https://github.com/user-attachments/assets/a0aabcfb-184b-4811-8a09-51b30a5bb492)

**Comment by tyrannus00** [comment]
Thanks for reporting the issue, will publish a version with the fix soon
