### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by forditt** [tyrannus00/CleanF3#3]
After i open the mod menu through the mod menu the game crashes.
I am using version 1.19.3
![зображення](https://user-images.githubusercontent.com/105544922/218506913-df37965c-75c2-4634-9daa-673ba36f7315.png)

**Comment by tyrannus00** [comment]
Thanks for reporting the issue, I have published a new release that fixes this bug. You can grab it from the releases or the modrinth site.
