### ISSUE TITLE
Support more mods

### ISSUE THREAD

**Issue by forditt** [tyrannus00/CleanF3#4]
Please add an option not to display debug data of such mods as:
- [Entity Culling](https://www.curseforge.com/minecraft/mc-mods/entityculling)
- [Litematica](https://www.curseforge.com/minecraft/mc-mods/litematica)
- [ViaFabric](https://www.curseforge.com/minecraft/mc-mods/viafabric)

![зображення](https://user-images.githubusercontent.com/105544922/226106434-39dddca8-5037-48a7-b4f4-c8afe2880a7d.png)

**Comment by tyrannus00** [comment]
That's a good suggestion, I'll look into that

**Comment by forditt** [comment]
thank you

**Comment by tyrannus00** [comment]
Implemented for all 3 mods, next release will contain those features
