### ISSUE TITLE
Hide ImmediatelyFast and Presence footsteps debug info

### ISSUE THREAD

**Issue by RaptaG** [tyrannus00/CleanF3#5]
- https://modrinth.com/mod/immediatelyfast
- https://modrinth.com/mod/presence-footsteps

![debug-texts](https://user-images.githubusercontent.com/77157639/230731085-c8de4210-3325-4184-bf1c-9d51f06fc814.png)

**Comment by RaptaG** [comment]
Also, is there a way to minify the `NoiceRouter T` text? Maybe give it some new lines?

**Comment by RaptaG** [comment]
@tyrannus00

**Comment by DreamSt4n** [comment]
ImmediatelyFast Buffer Pool can be hidden in the config file.

**Comment by RaptaG** [comment]
👍🏽

**Comment by tyrannus00** [comment]
I just implemented compat with Presence Footsteps, so the next release will have this feature

**Comment by RaptaG** [comment]
Thanks!!
