### ISSUE TITLE
Distant Horizons + Vanilla String

### ISSUE THREAD

**Issue by MicrocontrollersDev** [tyrannus00/CleanF3#7]
- https://modrinth.com/mod/distanthorizons

![image](https://github.com/tyrannus00/CleanF3/assets/66657148/c3d2414c-d10e-4680-931b-0cc13fd4d606)

- Vanilla string that says F3+Q, I think most people using mods probably know this by now, doesn't really provide anything useful

![image](https://github.com/tyrannus00/CleanF3/assets/66657148/44ef7e2d-3277-440e-9569-fb0b4ab80914)

**Comment by tyrannus00** [comment]
Thanks for the suggestion, I implemented this into the new release
