### ISSUE TITLE
ImmediatelyFast Mod F3 Information

### ISSUE THREAD

**Issue by veeonthewall** [tyrannus00/CleanF3#8]
The mod ImmediatelyFast contains a small amount of information in the f3 menu. 
<img width="127" alt="Screen Shot 2023-05-22 at 3 45 05 PM" src="https://github.com/tyrannus00/CleanF3/assets/105337781/ba619e80-dee1-4b0e-afcf-6cb679775044">

**Comment by tyrannus00** [comment]
You can turn that off in Immediately fasts config
